/* This file was automatically generated.  Do not edit! */
#undef INTERFACE
int killCommand();
void BACKTRACK();
void CJPI();
void BJPI();
void clear();
void CLEAR();
void PEEK();
void pop();
void POP();
void push();
void PUSH();
void CW_D(int r,int c);
void CWD();
void CW_U(int r,int c);
void CWU();
void CW_R(int r,int c);
void CWR();
void CW_L(int r,int c);
void CWL();
void MOVE_D();
void MOVE_U();
void MOVE_R();
void MOVE_L();
void placeMarker(int r,int c);
void consume(int cost);
void MARK();
extern int spaces;
extern int itchRight;
extern int itchLeft;
extern int itchDown;
extern int itchUp;
extern int energy;
extern int mem_c;
extern int mem_r;
extern int pos_c;
extern int pos_r;
