/* This file was automatically generated.  Do not edit! */
#undef INTERFACE
void BACKTRACK();
void CJPI();
void BJPI();
void CLEAR();
void PEEK();
void POP();
void setEnergy(int e);
void PUSH();
void CWD();
void CWU();
void CWR();
void CWL();
void MOVE_D();
void MOVE_U();
void MOVE_R();
void MOVE_L();
void logger(char *str);
void runTick();
void setMem_c(int c);
void setMem_r(int r);
void setPos_c(int c);
void setPos_r(int r);
int getMem_c();
int getMem_r();
int getPos_c();
int getPos_r();
void setSpaces(int s);
void MARK();
void quitCode();
